<a href="https://colab.research.google.com/github/r1manyadav/calculator/blob/ml-models/netflix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#loading data

In [77]:
import pandas as pds
df = pd.read_csv('/content/movies.csv')

In [78]:
df.head()

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton

In [79]:
df.columns

Index(['index', 'budget', 'genres', 'homepage', 'id', 'keywords',
       'original_language', 'original_title', 'overview', 'popularity',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title',
       'vote_average', 'vote_count', 'cast', 'crew', 'director'],
      dtype='object')

In [ ]:
#preprocessing

In [80]:
df.drop(columns=['index', 'homepage', 'id', 'keywords',"budget",
       'original_language', 'original_title', 'overview', 'popularity',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'status', 'tagline'
       , 'vote_count', 'cast'],axis=1,inplace=True)

In [82]:
df.isnull().sum()

genres              28
spoken_languages     0
title                0
vote_average         0
crew                 0
director            30
dtype: int64

In [83]:
df.dropna(inplace=True)

In [84]:
df.drop_duplicates(inplace=True)

In [85]:
df.head()

,genres,spoken_languages,title,vote_average,crew,director
0,Action Adventure Fantasy Science Fiction,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Avatar,7.2,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,Adventure Fantasy Action,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Pirates of the Caribbean: At World's End,6.9,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,Action Adventure Crime,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Spectre,6.3,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,Action Crime Drama Thriller,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",The Dark Knight Rises,7.6,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,Action Adventure Science Fiction,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",John Carter,6.1,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton

In [87]:
df.rename(columns={'vote_average': 'rating'}, inplace=True)

In [88]:
df.head()

,genres,spoken_languages,title,rating,crew,director
0,Action Adventure Fantasy Science Fiction,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Avatar,7.2,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,Adventure Fantasy Action,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Pirates of the Caribbean: At World's End,6.9,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,Action Adventure Crime,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Spectre,6.3,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,Action Crime Drama Thriller,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",The Dark Knight Rises,7.6,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,Action Adventure Science Fiction,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",John Carter,6.1,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton

In [ ]:
#making data ready for transformation

In [89]:
df['features']=df['genres']+' '+df['director']+' '+df['spoken_languages']+' '+df['rating'].astype(str)

In [90]:
df['features'].head()

0    Action Adventure Fantasy Science Fiction James...
1    Adventure Fantasy Action Gore Verbinski [{"iso...
2    Action Adventure Crime Sam Mendes [{"iso_639_1...
3    Action Crime Drama Thriller Christopher Nolan ...
4    Action Adventure Science Fiction Andrew Stanto...
Name: features, dtype: object

In [ ]:
#converting data to numerical format so that model can understand

In [91]:
from sklearn.feature_extraction.text import TfidfVectorizer
vect=TfidfVectorizer(stop_words='english')
features_matrix=vect.fit_transform(df['features'])

In [98]:
print(features_matrix.shape)

(4759, 3154)

In [ ]:
#making similarity matrix

In [95]:
from sklearn.metrics.pairwise import cosine_similarity
similarity_matrix=cosine_similarity(features_matrix)

In [ ]:
#function for recommendation

In [104]:
def recommend(movie_name, top_n=5):
    if movie_name not in df["title"].values:
        return "Movie not found"

    movie_index = df[df["title"] == movie_name].index[0]

    similarity_scores = list(enumerate(similarity_matrix[movie_index]))
    similarity_scores = sorted(similarity_scores, key=lambda x: x[1], reverse=True)

    recommendations = []
    for i in similarity_scores[1:top_n+1]:
        recommendations.append(df.iloc[i[0]]["title"])

    return recommendations

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
similarity_matrix=cosine_similarity(features_matrix)

In [ ]:
#test run

In [102]:
recommend("Dangal")

'Movie not found'

In [108]:
recommend('Avatar')

['Terminator 2: Judgment Day',
 'The Abyss',
 'The Terminator',
 'Aliens',
 'The Wolverine']

In [109]:
recommend('The Dark Knight Rises')

['Insomnia', 'The Prestige', 'Memento', 'Interstellar', 'The Dark Knight']

In [107]:
recommend('John Carter')

["A Bug's Life", 'WALL·E', 'Finding Nemo', 'The Host', 'Chain Reaction']

In [ ]:
#recommending similiar movies :)